services:
  - type: web
    name: geoapi
    env: python
    plan: free
    autoDeploy: false
    healthCheckPath: /
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn --app-dir src app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ORS_API_KEY
        sync: false
