from typing import Protocol, Iterable, Optional
from uuid import UUID
from domain.entities.book import Book

class BookQuery(Protocol):
    def get(self, id:UUID) -> Optional[Book]: ...
    def list(self) -> Iterable[Book]: ...
    def exists_title(self, title:str) -> bool: ...

class BookCommand(Protocol):
    def add(self, book:Book) -> None: ...
    def update(self, book:Book) ->None: ...
    def delete(self, id: UUID) -> None: ...

#las interfaces de .net en python se llaman Protocols.
#los ... signfica que no hacemos nada, pero se declara.